"""fixing  this

Revision ID: f4f8b8b4710c
Revises: be05f0d10af3
Create Date: 2023-11-16 18:39:42.139784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f8b8b4710c'
down_revision = 'be05f0d10af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earthquakes', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earthquakes', 'year')
    # ### end Alembic commands ###
